### ISSUE TITLE
Laravel can not cache config file

### ISSUE THREAD

**Issue by vaanholtje** [ckfinder/ckfinder-laravel-package#10]
When Laravel tries to cache the config file i get an error that it can not cache the ckfinder config file.
Duo the authentication callable laravel configs may not contain a callable.

**Using Laravel 5.7**
How to reproduce after publishing the config of this package run:
```
php artisan config:cache
```

How could we fix this?

**Comment by vaanholtje** [comment]
@zaak Bump  already news ont his issue?

**Comment by zaak** [comment]
This issue has been fixed in the latest version. Authentication uses now a middleware: https://github.com/ckfinder/ckfinder-laravel-package#configuring-authentication
