### ISSUE TITLE
Cannot GET /public/js/ckfinder/core/connector/php/connector.php

### ISSUE THREAD

**Issue by probitaille** [ckfinder/ckfinder-laravel-package#105]
After completing all the installation steps for Laravel, there is no core folder. 

![image](https://github.com/ckfinder/ckfinder-laravel-package/assets/2374739/fcf722d5-0441-441e-bfa0-199df534e539)

![image](https://github.com/ckfinder/ckfinder-laravel-package/assets/2374739/bfadccf1-1bc5-4772-a5a7-3dfb97a1408d)

**Comment by zaak** [comment]
@probitaille: What Laravel version do you use?

**Comment by probitaille** [comment]
The problem is on my side. I just recreate a brand new Lavarel project with the latest version and it's working as expected.

I just recreate the whole process in my actual project and everything works fine.
I probably miss a step, I blame a problem with my router.
