### ISSUE TITLE
The file browser is disabled for security reasons

### ISSUE THREAD

**Issue by Askancy** [ckfinder/ckfinder-laravel-package#14]
I tried installing ckfinder in my Laravel 5.8, but I get this error when I open the modal

> The file browser is disabled for security reasons. Please contact your system administrator and check the CKFinder configuration file.

What can the error be?

I created the middleware:
`$config['authentication'] = '\App\Http\Middleware\CKFinderAuth';`
```     public function handle($request, Closure $next)
     {
         config(['ckfinder.authentication' => function() {
             return true;
         }]);
         return $next($request);
     }
```

should I declare it also in the kernel.php?

**Comment by zaak** [comment]
Hi @Askancy. I have just checked Laravel 5.8 and everything seems to work fine. Have you tried clearing the cache with `artisan cache:clear`? [Refreshing the Composer's autoload](https://getcomposer.org/doc/03-cli.md#dump-autoload-dumpautoload-) might help too.

> should I declare it also in the kernel.php?

It is not required to register the middleware there. CKFinder will register it automatically on controller level using the class defined in `$config['authentication'] = '\App\Http\Middleware\CKFinderAuth';`.

**Comment by Askancy** [comment]
Again with: The file browser is disabled for security reasons. Please contact your system administrator and check the CKFinder configuration file.

in the middleware I used the code you provided for example
```
<?php

namespace App\Http\Middleware;

use Closure;

class CKFinderAuth
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
     public function handle($request, Closure $next)
     {
         config(['ckfinder.authentication' => function() {
             return true;
         }]);
         return $next($request);
     }
}

```

**Comment by zaak** [comment]
@Askancy: Could you please contact us through the [support channel](https://ckeditor.com/contact/)? We could then discuss the configuration details that might be considered sensitive in a public discussion.

**Comment by Askancy** [comment]
work was a local problem, on server is ok.  I wanted to ask something. I have to select a category via a bootstrap-select, depending on the selection I need the CKFinder to go to a specific folder, is it possible to address the default folder via javascript?
