### ISSUE TITLE
My uploadUrl not work

### ISSUE THREAD

**Issue by marinalans** [ckfinder/ckfinder-laravel-package#15]
`  ckfinder: {
 uploadUrl: '../ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json'
 }
 `

**Comment by zaak** [comment]
Hi @marinalans. This `uploadUrl` is invalid. Please have a look at examples included in this package ([here's how to enable them](https://github.com/ckfinder/ckfinder-laravel-package#usage) - one of them shows the setup in CKEditor 5.

The `uploadUrl` in your case can be defined like this:

```js
ClassicEditor
    .create( document.querySelector( '#editor2' ), {
        ckfinder: {
            // Use named route for CKFinder connector entry point
            uploadUrl: '{{ route('ckfinder_connector') }}?command=QuickUpload&type=Files'
        }
    } )
    .catch( error => {
        console.error( error );
    } );

```

**Comment by marinalans** [comment]
Thank you!
But my publication not save.. and I don't understand why
Whats is the problem in my code?

![laravel with kcfinder](https://user-images.githubusercontent.com/14960123/59439915-16f87980-8dc4-11e9-9790-60aefbc023ba.jpg)

**Comment by zaak** [comment]
@marinalans: I believe it's a matter of configuration in `configckfinder.php`. Please have a look at the `baseUrl` configured for the `backend`. [Here](https://ckeditor.com/docs/ckfinder/ckfinder3-php/configuration.html#configuration_options_backends) you can read more about `backend` configuration options.

If the above doesn't help then feel free to contact us through the [official support channel](https://ckeditor.com/contact/), so we can discuss the configuration details.

**Comment by marinalans** [comment]
I think that's ok.

![config](https://user-images.githubusercontent.com/14960123/59441341-6cce2100-8dc6-11e9-889a-cec1af9da203.jpg)

Thanks for your help
