### ISSUE TITLE
Route [ckfinder_connector] not defined. 

### ISSUE THREAD

**Issue by zacksleo** [ckfinder/ckfinder-laravel-package#22]
When I cached the route via `php artisan route:cache`, puted `@include('ckfinder::setup')` in the page then access the page. I got error called `Route [ckfinder_connector] not defined. `. How to fix that?

**Comment by ducit1995** [comment]
try 
`php artisan cache:clear
php artisan view:clear
php artisan route:clear
php artisan config:clear`

**Comment by zacksleo** [comment]
First I have to clear route cache every time. Second when I create route cache the bug comes again.

**Comment by marooj** [comment]
i am have the same problem please help me

**Comment by sestriel** [comment]
Got the same problem.
This happens only when the routes are cached by `php artisan route:cache`.
If I do not cache the routes, or clear the route cache (`php artisan route:clear`), everything works fine.

Any fix for this?

**Comment by marooj** [comment]
my problem solved after php artisan route:cache but the new problem is :

>  CKFinder Authentication config field must be a PHP callable

**Comment by marooj** [comment]
after edit vendor\ckfinder\ckfinder-laravel-package\src\routes.php and append middleware to :
`
Route::group(['middleware'=>['CustomCKFinderAuth']], function() {
    Route::any('/ckfinder/connector', 'CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')
        ->name('ckfinder_connector');

    Route::any('/ckfinder/browser', 'CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')
        ->name('ckfinder_browser');
});
`

my problem solved .
but you must create a way that middleware append without change plugin 
thank you

**Comment by sestriel** [comment]
@marooj just refer to the documentation, setting the authentication var in /config/ckfinder.php to:
`$config['authentication'] = '\App\Http\Middleware\CustomCKFinderAuth';`
would also solving your problem.
Also, if your problem is solved by running `php artisan:cache`, you have not the same problem as we have.

**Comment by marooj** [comment]
@sestriel yes, i am do it $config['authentication'] = '\App\Http\Middleware\CustomCKFinderAuth'; but i am said you must create a way that middleware append without change plugin  because after add middleware to route of plugin in vendor`s folder  my problem solved .

**Comment by nixprosoft** [comment]
Working solution is only NOT to use `@php artisan route:cache`.
But it is NOT artisan's way! I have a big project with many routes needed to be cached.

Changing `vendor/ckfinder/ckfinder-laravel-package/src/routes.php` NOT worked for me.

Copying vendor routes to `routes/web.php` worked partially:

- namespace for route group need to be set to `\CKSource\CKFinderBridge\Controller`
- middleware must be named with full namespace `\App\Http\Middleware\CustomCKFinderAuth`
- CKEdittor & CKFinder starts normally, but when you try to delete a file - 419 error appears
- if you add `/ckeditor/*` to `app/Http/Middleware/VerifyCsrfToken.php` `$except=[]` and try to delete the file - appears 400 error

**Comment by nixprosoft** [comment]
> my problem solved after php artisan route:cache but the new problem is :
> 
> > CKFinder Authentication config field must be a PHP callable

Maybe namespace like `\App\Http\Middleware\CustomCKFinderAuth` will help?

**Comment by fri3ndly** [comment]
I'm facing the same issue - I'm referencing custom authentication file from a package and it's defined in my ckfinder.php config file, but running `php artisan optimize` on production prevents ckfinder from working

**Comment by SnakeWar** [comment]
I fixed with composer install, after deleted the vendor folder.

**Comment by BernhardK91** [comment]
I had this issue after updating the package. It seams there is a new config parameter. I fixed the issue by adding 

`$config['loadRoutes'] = true;`

to my config/ckfinder.php.
