### ISSUE TITLE
Can't used in Laravel 6.*

### ISSUE THREAD

**Issue by brightjune** [ckfinder/ckfinder-laravel-package#28]
Hi,

Package can't used in Laravel 6.*

Thanks

**Comment by mrkhosravian** [comment]
Same Issue :(

**Comment by brightjune** [comment]
laravel/framework: "^5.5|^6.0"

**Comment by fourn** [comment]
Same Issue :(

**Comment by sebastiansulinski** [comment]
Any plan to fix this please?

**Comment by holfbroy** [comment]
same issue, please add support for Laravel 6.0 -  implement merge request (https://github.com/ckfinder/ckfinder-laravel-package/pull/27 )

**Comment by mszabeh** [comment]
same issue :(

**Comment by lgy605** [comment]
same issue :(

**Comment by lgy605** [comment]
please add support for Laravel 6.0 - implement merge request (#27 )

**Comment by vokiel** [comment]
Apologies for taking so long to merge this pull request.

Thank you @RamyTalal for your contribution!

**Comment by vokiel** [comment]
We released a new version with Laravel v6.x support, see
- https://github.com/ckfinder/ckfinder-laravel-package/releases/tag/v3.5.1.1
- https://packagist.org/packages/ckfinder/ckfinder-laravel-package
