### ISSUE TITLE
Error Route default

### ISSUE THREAD

**Issue by josuelmm** [ckfinder/ckfinder-laravel-package#29]
Good morning, I have the following error .. When loading the ckfinder ..
The way I solved it was creating the route
`Route::any('/AppBase/public/js/ckfinder/core/connector/php/connector.php', 'CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')
    ->name('ckfinder_connector_base');`

<img src="https://i.imgur.com/38zAkKZ.png">

But I want to use the default route that is
`Route::any('/ckfinder/connector', 'CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')
    ->name('ckfinder_connector');`

Any idea why that Error.

**Comment by josuelmm** [comment]
Somebody Help...

**Comment by zaak** [comment]
Fixed in https://github.com/ckfinder/ckfinder-laravel-package/pull/41.
