### ISSUE TITLE
league/flysystem dependency conflict

### ISSUE THREAD

**Issue by jonjrwhite** [ckfinder/ckfinder-laravel-package#3]
Trying to install `ckfinder-laravel-package` on one of my projects threw up a conflict with the latest `league/flysystem` version already installed.

I've created a PR that tweaks the `league/flysystem` composer dependencies.

It seems to be working on my local environment but I've not extensively tested it.

**Comment by khessels** [comment]
as a temp workaround for composer require league/flysystem:1.0.45

**Comment by jason-beach** [comment]
+1
I'm also having issues with installing this for my laravel project. Needing an update on the `league/flysystem` version already installed as @jonjrwhite has indicated. 

Any updates on his pull request?
#2

**Comment by Anatoliy-Gerasimov** [comment]
+1

**Comment by zaak** [comment]
Resolved in https://github.com/ckfinder/ckfinder-laravel-package/pull/5.
