### ISSUE TITLE
Not satisfiable with Laravel 6

### ISSUE THREAD

**Issue by mr-khuja** [ckfinder/ckfinder-laravel-package#30]

**Comment by Trucnt** [comment]
Hey @RamyTalal , can you add support for Laravel **6.x** instead fixed 6.0  (https://github.com/ckfinder/ckfinder-laravel-package/commit/501741ea000e9f0760c8067cfb68d47ce6a9cf63)
Tks.

**Comment by lgy605** [comment]
Laravel 6.x Installation unsuccessful

**Comment by vokiel** [comment]
Fixed with https://github.com/ckfinder/ckfinder-laravel-package/commit/3b604d3afba8b9d47492f68d82f18da10f5ce12c

**Comment by vokiel** [comment]
We released a new version with Laravel v6.x support, see
- https://github.com/ckfinder/ckfinder-laravel-package/releases/tag/v3.5.1.1
- https://packagist.org/packages/ckfinder/ckfinder-laravel-package
