### ISSUE TITLE
CKFinder Authentication config field must be a PHP callable

### ISSUE THREAD

**Issue by f0rx** [ckfinder/ckfinder-laravel-package#4]
I just installed CKFinder in my Laravel application, and I always receive this error --: CKFinder Authentication config field must be a PHP callable -- when I browse the ckfinder url. Can anyone point out the issue here?? Thanks

**Comment by qqjt** [comment]
chekc `$config['authentication']` in `config/ckfinder.php` .

**Comment by zaak** [comment]
This issue has been fixed in the latest version. Authentication uses now a middleware: https://github.com/ckfinder/ckfinder-laravel-package#configuring-authentication

**Comment by marooj** [comment]
but i am have same problem i am doing step by step by your instruction but get this error
