### ISSUE TITLE
Laravel 7 error 500 internal server

### ISSUE THREAD

**Issue by K1-Aria** [ckfinder/ckfinder-laravel-package#47]
it seems this package is not working in laravel 7.6 and i have 500 server error in this request:
http://localhost:8000/ckfinder/connector?command=Init&lang=en

**Comment by HAPXu3** [comment]
Did you create middleware as written [here](https://github.com/ckfinder/ckfinder-laravel-package#configuring-authentication)?

**Comment by K1-Aria** [comment]
yes

**Comment by HAPXu3** [comment]
Can you give the full text of the error message? Because I also had a 500 error due to the lack of gd library.

**Comment by K1-Aria** [comment]
see this image:

https://programdan.ir/err/finderErr.jpeg

**Comment by HAPXu3** [comment]
Yes, it really is a problem. Perhaps this happened due to the transition of Laravel 7 to the Symfony 5 engine - events in HttpKernel changed there.

**Comment by K1-Aria** [comment]
what should i do??
What filemanager package can I use in Laravel 7

**Comment by HAPXu3** [comment]
[Here](https://github.com/ckfinder/ckfinder-laravel-package/issues/42#issuecomment-621821561), the maintainer announced that an update for this issue will be released next week.

**Comment by zaak** [comment]
Support for Laravel 7 has been added in just released `v3.5.1.4`.
