### ISSUE TITLE
How management files via Mysql Database

### ISSUE THREAD

**Issue by dinhbang** [ckfinder/ckfinder-laravel-package#48]
Hello,

I am migration news site to Laravel. The images and document files are management via files table ( storing file name, path). My question How I can use ckfinder with existing files table in Mysql?

Best regards,
Bang.

**Comment by zaak** [comment]
Hi @dinhbang. To store files in the database you have to create an appropriate file system adapter.
[Here](https://ckeditor.com/docs/ckfinder/ckfinder3-php/howto.html#howto_custom_storage) you can find an article describing how to implement a plugin that adds support for storing files in a database. [Here](https://github.com/ckfinder/ckfinder-plugin-database-adapter-php) you can find the code.

I hope you will find the above info helpful.

**Comment by dinhbang** [comment]
Hi @zaak Thank for your support. My mean not storing data file in database. The database is only storing file name and path file. Sample the image test.png in files/articles/test.png. Then the files table is only name is test.png and path is files/articles, It is not including Binary image data in database

**Comment by zaak** [comment]
Thank you for the clarification @dinhbang, but the answer remains the same - you have to implement a custom storage adapter.

**Comment by dinhbang** [comment]
@zaak Thank you so much! I will learn to modify this database adapter.
