### ISSUE TITLE
Support Laravel 8.*

### ISSUE THREAD

**Issue by vinhphamduc** [ckfinder/ckfinder-laravel-package#54]

**Comment by pesovski** [comment]
Yeap, I can't upgrade Laravel to version 8 because of this package. Any ETA on when will these 2 be compatible?

**Comment by vinhphamduc** [comment]
@pesovski : Wait for ckfinder update, I was fork new repository to https://github.com/vinhphamduc/ckfinder and update support for Laravel 8. You can using my repository for Laravel 8.

Add this line to composer.json file
"repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:vinhphamduc/ckfinder.git"
        }
    ],

**Comment by zaak** [comment]
@vinhphamduc: Feel free the send a pull request :slightly_smiling_face:

**Comment by zaak** [comment]
Thank you @vinhphamduc. The new version is out.
