### ISSUE TITLE
Error In ServiceProvider.php line 173:  array_key_exists(): The first argument should be either a string or an integer

### ISSUE THREAD

**Issue by sourov06** [ckfinder/ckfinder-laravel-package#62]
While I stack trace that error I found this:

[2021-03-25 09:20:58] local.ERROR: array_key_exists(): The first argument should be either a string or an integer {"exception":"[object] (ErrorException(code: 0): array_key_exists(): The first argument should be either a string or an integer at F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\ServiceProvider.php:173)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'array_key_exist...', 'F:\\\\wamp64\\\\www\\\\o...', 173, Array)
#1 F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\ServiceProvider.php(173): array_key_exists(Array, Array)
#2 F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\ServiceProvider.php(147): Illuminate\\Support\\ServiceProvider->addPublishGroup(Array, Array)
#3 F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\ckfinder\\ckfinder-laravel-package\\src\\CKFinderServiceProvider.php(27): Illuminate\\Support\\ServiceProvider->publishes(Array, Array)
#4 [internal function]: CKSource\\CKFinderBridge\\CKFinderServiceProvider->boot()
#5 F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(29): call_user_func_array(Array, Array)
#6 F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#8 F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#9 F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(794): Illuminate\\Container\\Container->call(Array)
#10 F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(777): Illuminate\\Foundation\\Application->bootProvider(Object(CKSource\\CKFinderBridge\\CKFinderServiceProvider))
#11 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(CKSource\\CKFinderBridge\\CKFinderServiceProvider), 15)
#12 F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(778): array_walk(Array, Object(Closure))
#13 F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#14 F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(206): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#15 F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(297): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#16 F:\\wamp64\\www\\oasis.kz\\oasis_new\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(120): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#17 F:\\wamp64\\www\\oasis.kz\\oasis_new\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 {main}
"} 

**Laravel version 5.6. php version: 7.4**

**Comment by atlantisguru** [comment]
Same here with Laravel 5.6, PHP 7.1, Ubuntu 18.04 and it completely killed artisan CLI.

**Comment by atlantisguru** [comment]
I found the solution here: #52
