### ISSUE TITLE
Laravel 8 problems: install with composer

### ISSUE THREAD

**Issue by hamzaPlanet** [ckfinder/ckfinder-laravel-package#68]
Problem 1
    - ckfinder/ckfinder-laravel-package[v3.5.1.6, ..., v3.5.2] require league/flysystem-aws-s3-v3 ^1.0.13 -> satisfiable by league/flysystem-aws-s3-v3[1.0.13, ...,
 1.0.x-dev (alias of dev-master)].
    - league/flysystem-aws-s3-v3[1.0.13, ..., 1.0.25] require aws/aws-sdk-php ^3.0.0 -> satisfiable by aws/aws-sdk-php[3.0.0-beta.1, ..., 3.186.1].
    - league/flysystem-aws-s3-v3 1.0.x-dev is an alias of league/flysystem-aws-s3-v3 dev-master and thus requires it to be installed too.
    - aws/aws-sdk-php 3.0.x-dev is an alias of aws/aws-sdk-php dev-master and thus requires it to be installed too.
    - league/flysystem-aws-s3-v3[dev-master, 1.0.26, ..., 1.0.29] require aws/aws-sdk-php ^3.20.0 -> satisfiable by aws/aws-sdk-php[3.20.0, ..., 3.186.1].
    - ckfinder/ckfinder-laravel-package v3.5.1 requires laravel/framework ^5.5 -> found laravel/framework[v5.5.0, ..., 5.8.x-dev] but it conflicts with your root c
omposer.json require (^8.40).
    - ckfinder/ckfinder-laravel-package[v3.5.1.1, ..., v3.5.1.2] require laravel/framework ^5.5|~6.0 -> found laravel/framework[v5.5.0, ..., 5.8.x-dev, v6.0.0, ...
, 6.x-dev] but it conflicts with your root composer.json require (^8.40).
    - ckfinder/ckfinder-laravel-package[v3.5.1.3, ..., v3.5.1.5] require laravel/framework ^5.5|~6.0|~7.0 -> found laravel/framework[v5.5.0, ..., 5.8.x-dev, v6.0.0
, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8.40).
    - aws/aws-sdk-php[dev-master, 3.173.20, ..., 3.186.1] require guzzlehttp/psr7 ^1.7.0 -> found guzzlehttp/psr7[1.7.0, ..., 1.x-dev] but the package is fixed to
2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - aws/aws-sdk-php 3.0.0-beta.1 requires guzzlehttp/guzzle ~5.0 -> found guzzlehttp/guzzle[5.0.0, ..., 5.3.x-dev] but it conflicts with your root composer.json
require (^7.0.1).
    - aws/aws-sdk-php 3.0.0 requires guzzlehttp/guzzle ^5.3 || ^6.0.1 -> found guzzlehttp/guzzle[5.3.0, ..., 5.3.x-dev, 6.0.1, ..., 6.5.x-dev] but it conflicts wit
h your root composer.json require (^7.0.1).
    - aws/aws-sdk-php[3.0.1, ..., 3.3.4] require guzzlehttp/psr7 ~1.0 -> found guzzlehttp/psr7[1.0.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file ve
rsion) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - aws/aws-sdk-php[3.3.5, ..., 3.18.28] require guzzlehttp/guzzle ~5.3|~6.0.1|~6.1 -> found guzzlehttp/guzzle[5.3.0, ..., 5.3.x-dev, 6.0.1, ..., 6.5.x-dev] but
it conflicts with your root composer.json require (^7.0.1).
    - aws/aws-sdk-php 3.18.29 requires guzzlehttp/guzzle ~5.3.1|~6.2.1 -> found guzzlehttp/guzzle[5.3.1, ..., 5.3.x-dev, 6.2.1, 6.2.2, 6.2.3] but it conflicts with
 your root composer.json require (^7.0.1).
    - aws/aws-sdk-php[3.18.30, ..., 3.69.10] require guzzlehttp/guzzle ^5.3.1|^6.2.1 -> found guzzlehttp/guzzle[5.3.1, ..., 5.3.x-dev, 6.2.1, ..., 6.5.x-dev] but i
t conflicts with your root composer.json require (^7.0.1).
    - aws/aws-sdk-php[3.69.11, ..., 3.130.3] require guzzlehttp/guzzle ^5.3.3|^6.2.1 -> found guzzlehttp/guzzle[5.3.3, 5.3.4, 5.3.x-dev, 6.2.1, ..., 6.5.x-dev] but
 it conflicts with your root composer.json require (^7.0.1).
    - aws/aws-sdk-php[3.131.0, ..., 3.173.19] require guzzlehttp/psr7 ^1.4.1 -> found guzzlehttp/psr7[1.4.1, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock
file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires ckfinder/ckfinder-laravel-package ^3.5 -> satisfiable by ckfinder/ckfinder-laravel-package[v3.5.1, ..., v3.5.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by ducconit** [comment]
`composer require ckfinder/ckfinder-laravel-package -W`
