### ISSUE TITLE
Hello. Are you planning to update support for Laravel 9? How soon? Thank you

### ISSUE THREAD

**Issue by hungphamlk** [ckfinder/ckfinder-laravel-package#72]

**Comment by flyinglb** [comment]
how soon???

**Comment by Freeeon** [comment]
Waiting so looong...

**Comment by presleyd** [comment]
Ok apparently this is al answered in #84

**Comment by zaak** [comment]
Support for Laravel 9 has been added in the latest version. Please update `ckfinder/ckfinder-laravel-package`.
