### ISSUE TITLE
Laravel 9 is not support when will you update

### ISSUE THREAD

**Issue by Khatri-Ran-Bahadur** [ckfinder/ckfinder-laravel-package#73]

**Comment by d4rkr3pt0r** [comment]
I'm waiting for an update as well

**Comment by lanstar2** [comment]
I'm waiting for an update as well

**Comment by TraLeeee** [comment]
Hope they will update soon.

**Comment by flyinglb** [comment]
me too

**Comment by zaak** [comment]
Support for Laravel 9 has been added in the latest version. Please update `ckfinder/ckfinder-laravel-package`.

**Comment by Khatri-Ran-Bahadur** [comment]
But this is not merge in main branch.

this command is not working yet
 composer require ckfinder/ckfinder-laravel-package



[image: created with MySignature.io]
<https://mysignature.io/?utm_source=logo>

Ran Bahadur kc
 *Sathisoft Pvt. Ltd.* | Full Stack Developer
*Mobile**:*  9868620708
*Email:*  ***@***.*** ***@***.***>
*Skype:*  9868620708
*Address:*  Aathbiskot, 6 Holi, Rukum, Nepal
[image: created with MySignature.io] <https://www.facebook.com/rn.khatri.5>
[image: created with MySignature.io] <https://twitter.com/ran59869687>
[image: created with MySignature.io]
<https://www.linkedin.com/in/ran-bahadur-kc-645951156/>
<https://mysignature.io/editor/?utm_source=freepixel>

**Comment by bmlotek** [comment]
Hello, 

If our laravel project requirements meets package requirements command "composer require ckfinder/ckfinder-laravel-package" gets us version ^4.0 for ckfinder/ckfinder-laravel-package. Otherwise command will get lower version of package. Could you provide us some more details of what your problem is?
