### ISSUE TITLE
Laravel 9 - Symfony Issues

### ISSUE THREAD

**Issue by sitesurfer** [ckfinder/ckfinder-laravel-package#80]
There appears to be an issue with the latest Symfony HttpKernel when using Laravel 9 - I guess because it is using a more recent package?

The issue appears to be at Line 492 within CKFinder.php in the downloaded source and suggests that the Interface declaration is noncorrect.

I am keen to purchase CKFinder for a corporate - so please can we determine if this is a quick fix?

**Comment by zaak** [comment]
Support for Laravel 9 has been added in the latest version. Please update `ckfinder/ckfinder-laravel-package`.
