### ISSUE TITLE
When will release version for Laravel 9+?

### ISSUE THREAD

**Issue by huungoc1994hd** [ckfinder/ckfinder-laravel-package#87]
I'm using ckfinder for a project running NuxtJS on the client side and Laravel ver ^9.2 for the backend, but your package doesn't seem to support Laravel 9+. Please help !!!

**Comment by joshuacadman01** [comment]
Hopefully this will be supported soon!

**Comment by phongd3v** [comment]
install with command 
composer require muran2/ckfinder-laravel-9-package:*

**Comment by zaak** [comment]
Support for Laravel 9 has been added in the latest version. Please update `ckfinder/ckfinder-laravel-package`.
